### PR TITLE
Initial GIS activity for Taverna 3

### PR DESCRIPTION
**Pull request by edikaradumi**

### CODE REVIEW

**Comment by stain** [comment]
Thanks for your pull request!

What is the license of the `wps_config.xml` file? Did you make it or where did you get it from?

**Comment by stain** [comment]
I added the ASF headers and renamed your module folders to the simpler style `taverna-gis-activity` -- to pick up these changes make sure you do:

``` shell
    git checkout master
    git status
    # git commit ## if there were anything not committed
    git fetch apache
    git merge apache/master
    git push origin
```

(dev@taverna folks - I talked IRL with Edi to help him update his plugin to Taverna 3)

**Comment by edikaradumi** [comment]
I got wps_config.xml from 52North webapp project which in fact is under GNU GENERAL PUBLIC LICENSE Version 2, June 1991, but the file is not used so I will remove it

**Comment by stain** [comment]
Thank you for checking, that sounds right to remove it, as GPL 2 is incompatible with the Apache license.

**Comment by stain** [comment]
In fact it seems the whole `52n-wps-client-lib`  dependency would be incompatible :-(

From taverna-gis-clienttarget/classes/META-INF/DEPENDENCIES:

```
From: '52north.org' (http://www.52north.org/)
  - OGC OWS schema (spec. v1.1.0) (http://52north.org/maven/project-sites/52n-common-xml/52n-xml-ows-v110) org.n52.sensorweb:52n-xml-ows-v110:jar:1.1.0
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991  (http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt)
  - W3C xlink schema (spec. v1.1.0) (http://52north.org/maven/project-sites/52n-common-xml/52n-xml-xlink-v110) org.n52.sensorweb:52n-xml-xlink-v110:jar:1.0.0
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991  (http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt)
  - 52North WPS Client Library (https://wiki.52north.org/bin/view/Geoprocessing/ClientAPI) org.n52.wps:52n-wps-client-lib:jar:3.3.1
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991  (http://www.gnu.org/licenses/gpl-2.0.txt)
  - 52North WPS Commons (http://52north.org/wps/52n-wps-commons) org.n52.wps:52n-wps-commons:jar:3.3.1
    License: Apache License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0)
  - 52North WPS Input/Output API (http://52north.org/wps/52n-wps-io) org.n52.wps:52n-wps-io:jar:3.3.1
    License: Apache License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0)
  - 52North WPS Geotools Input/Ouput Implementation (http://52north.org/wps/52n-wps-io-geotools) org.n52.wps:52n-wps-io-geotools:jar:3.3.1
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991 (with Exceptions to EPL Libraries)  (https://raw.githubusercontent.com/52North/WPS/WPS-3.3.0/52n-wps-io-geotools/LICENSE)
  - 52North WPS Input/Ouput Implementation (http://52north.org/wps/52n-wps-io-impl) org.n52.wps:52n-wps-io-impl:jar:3.3.1
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991  (http://www.gnu.org/licenses/gpl-2.0.txt)
  - OGC WPS schema (spec. v1.0.0) (http://52north.org/maven/project-sites/52n-common-xml/52n-xml-wps-v100) org.n52.wps:52n-xml-wps-v100:jar:1.1.0
    License: GNU GENERAL PUBLIC LICENSE Version 2, June 1991  (http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt)
```

It would be OK as a `<scope>test</scope>` dependency, though, but not as a required runtime dependency.

**Comment by edikaradumi** [comment]
In fact, I already checked that but there is something mentioned in their licensing section http://52north.org/about/licensing

> Software Licensing
> 
> Currently, most of our software is published under the GNU GPL V.2 license. Most future developments will use the Apache 2.0 license or similar non copy-left licenses.

Do you think that for the moment it is ok to continue the development with the current library? The solution that we discussed on Monday about creating a gis-client project might help to replace the 52North library with another compatible library

**Comment by stain** [comment]
As we would want to (eventually) release `taverna-plugin-gis` from Apache Software Foundation we cannot require the use of a GPL dependency (even though 52North have added a [derivative work](https://github.com/52North/WPS/blob/dev/NOTICE#L8) exceptions, which I would say makes it as some kind of restricted LGPL variant) - however it would be OK to have it as an [optional dependency](https://www.apache.org/legal/resolved#optional).

Looking at the [different modules](https://github.com/52North/WPS#license) only 52n-wps-algorithm, 52n-wps-commons and 52n-wps-io are distributed under the compatible Apache License - but I guess you really need the `52n-wps-client-lib`?

I think it could work if we evolve `taverna-gis-client` to be a interface/impl split, and have `wps` as one of several implementation bindings, as long as users would not practically still be required to use the WPS binding for normal use.  But would that mean that you would have to make that additional other binding, or are there alternative client libraries you could reuse, which have an [ASF-permitted open source license](https://www.apache.org/legal/resolved)?

**Comment by edikaradumi** [comment]
Yes, I need the `52n-wps-client-lib`

I will have to implement the additional bindings. The libraries that I have researched so far have GPL licenses.

**Pull request merged**
